# Generated by Django 4.1.7 on 2023-02-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_squadra', models.CharField(max_length=100)),
                ('logo_squadra', models.ImageField(upload_to='loghi_squadre/')),
                ('indirizzo', models.CharField(max_length=200)),
                ('mappa', models.CharField(max_length=200)),
                ('orario_partita_di_casa', models.TimeField()),
            ],
            options={
                'verbose_name': 'Squadra',
                'verbose_name_plural': 'Squadre',
                'ordering': ['nome_squadra'],
            },
        ),
    ]
