# Generated by Django 4.1.7 on 2023-02-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Under17', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calciatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cognome_calciatore', models.CharField(help_text='inserisci il cognome', max_length=100)),
                ('nome_calciatore', models.CharField(help_text='inserisci il nome', max_length=100)),
                ('data_di_nascita', models.DateField()),
                ('immagine_calciatore', models.ImageField(upload_to='foto_calciatori/')),
                ('ruolo', models.CharField(choices=[(None, 'Seleziona il Ruolo'), ('P', 'Portiere'), ('D', 'Difensore'), ('C', 'Centrocampista'), ('A', 'Attaccante')], default='none', help_text='ruolo', max_length=1)),
            ],
            options={
                'verbose_name': 'Calciatore',
                'verbose_name_plural': 'Calciatori',
                'ordering': ['cognome_calciatore'],
            },
        ),
    ]
