# Generated by Django 4.1.7 on 2023-02-24 11:18

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('Under17', '0013_alter_calciatore_immagine_calciatore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calciatore',
            options={'ordering': [django.db.models.functions.text.Lower('cognome_calciatore')], 'verbose_name': 'Calciatore', 'verbose_name_plural': 'Calciatori'},
        ),
        migrations.AlterModelOptions(
            name='squadra',
            options={'ordering': [django.db.models.functions.text.Lower('nome_squadra')], 'verbose_name': 'Squadra', 'verbose_name_plural': 'Squadre'},
        ),
        migrations.AlterField(
            model_name='squadra',
            name='logo_squadra',
            field=models.ImageField(blank=True, default='../static/images/shield.png', upload_to='loghi_squadre/'),
        ),
        migrations.CreateModel(
            name='Partita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giornata', models.IntegerField()),
                ('data_partita', models.DateTimeField()),
                ('nome_squadra_casa', models.ManyToManyField(related_name='squadra_casa', to='Under17.squadra', verbose_name='Squadra')),
                ('nome_squadra_trasferta', models.ManyToManyField(related_name='squadra_trasferta', to='Under17.squadra', verbose_name='Squadra')),
            ],
            options={
                'verbose_name': 'Partita',
                'verbose_name_plural': 'Partite',
                'ordering': ['giornata'],
            },
        ),
    ]
