# Generated by Django 4.1.7 on 2023-03-04 09:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('Under17', '0013_alter_calciatore_immagine_calciatore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calciatore',
            options={'ordering': [django.db.models.functions.text.Lower('cognome_calciatore')], 'verbose_name': 'Calciatore', 'verbose_name_plural': 'Calciatori'},
        ),
        migrations.AlterModelOptions(
            name='squadra',
            options={'ordering': [django.db.models.functions.text.Lower('nome_squadra')], 'verbose_name': 'Squadra', 'verbose_name_plural': 'Squadre'},
        ),
        migrations.AlterField(
            model_name='squadra',
            name='logo_squadra',
            field=models.ImageField(blank=True, default='../static/images/shield.png', upload_to='loghi_squadre/'),
        ),
        migrations.CreateModel(
            name='Partita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giornata', models.IntegerField(unique=True)),
                ('data_partita', models.DateField(default=datetime.date.today)),
                ('ora_partita', models.TimeField(auto_now_add=True)),
                ('gol_casa', models.IntegerField(blank=True)),
                ('gol_trasferta', models.IntegerField(blank=True)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='casa', to='Under17.squadra')),
                ('trasferta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trasferta', to='Under17.squadra')),
            ],
            options={
                'verbose_name': 'Partita',
                'verbose_name_plural': 'Partite',
                'ordering': ['giornata'],
            },
        ),
    ]
