# Generated by Django 4.1.7 on 2023-02-24 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Under17', '0014_alter_calciatore_options_alter_squadra_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partita',
            name='nome_squadra_casa',
        ),
        migrations.RemoveField(
            model_name='partita',
            name='nome_squadra_trasferta',
        ),
        migrations.AddField(
            model_name='partita',
            name='nome_squadra_casa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='squadra_casa', to='Under17.squadra', verbose_name='Squadra'),
        ),
        migrations.AddField(
            model_name='partita',
            name='nome_squadra_trasferta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='squadra_trasferta', to='Under17.squadra', verbose_name='Squadra'),
        ),
    ]
