# Generated by Django 4.1.7 on 2023-03-04 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Under17', '0014_alter_calciatore_options_alter_squadra_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partita',
            name='ora_partita',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
