# Generated by Django 4.1.7 on 2023-03-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Under17', '0015_alter_partita_ora_partita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partita',
            name='gol_casa',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='partita',
            name='gol_trasferta',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
