# Generated by Django 4.1.7 on 2023-02-24 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Under17', '0015_remove_partita_nome_squadra_casa_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partita',
        ),
    ]
