# Generated by Django 4.1.7 on 2023-02-24 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Under17', '0016_delete_partita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_partita', models.DateTimeField()),
                ('giornata', models.IntegerField()),
                ('squadra_casa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='squadra_casa', to='Under17.squadra', verbose_name='squadra_casa')),
                ('squadra_trasferta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='squadra_trasferta', to='Under17.squadra', verbose_name='squadra_trasferta')),
            ],
            options={
                'verbose_name': 'Partita',
                'verbose_name_plural': 'Partite',
                'ordering': ['giornata'],
            },
        ),
    ]
