# Generated by Django 4.1.7 on 2023-02-25 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Under17', '0017_partita'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partita',
        ),
    ]
